fourth part
Baldinini/taxi-service pull request #4
Opened 2021-01-17 21:39 UTC by Baldinini

2021-01-18 08:12 UTC, YuraBondarenko requested changes
I didn't find CarServiceImpl

2021-01-18 08:12 UTC, yurwing commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +            createCarsDrivers(car);
I think it's redundant here, because we create car with empy list of drivers

2021-01-18 09:42 UTC, Baldinini commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +            createCarsDrivers(car);
done, "I didn't find CarServiceImpl" - I didn't change this class, that's why you can't find it here

2021-01-18 09:43 UTC, YuraBondarenko approved these changes

2021-01-18 12:15 UTC, KseniiaMakarova requested changes

2021-01-18 12:15 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +     `driver_name` VARCHAR(225) NOT NULL,
there is no need to indicate driver_ prefix for each column because the columns are located in drivers table

same for other column names in manufacturer and car tables

2021-01-18 12:15 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/CarDao.java
redundant empty line

2021-01-18 12:15 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/DriverDaoJdbc.java
> +
same

2021-01-18 12:15 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +
same

2021-01-18 12:15 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/DriverDaoJdbc.java
> +public class DriverDaoJdbc implements DriverDao {
```suggestion
public class DriverDaoJdbcImpl implements DriverDao {
```
same for other JdbcImpl classes

2021-01-18 12:15 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +        String getAllCar = "SELECT * FROM cars c "
```suggestion
        String getAllCars = "SELECT * FROM cars c "
```

2021-01-18 12:15 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +        String deleteCarsDrivers = "DELETE FROM cars_drivers WHERE car_id = ?;";
let's better move the logic of deleting from `cars_drivers` into a separate method as well

2021-01-18 12:15 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +            createCarsDrivers(car);
move this line out of the `try` block - at the moment you opened one connection inside of another

2021-01-18 12:15 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +            for (int i = 0; i < car.getDrivers().size(); i++) {
```suggestion
            for (Driver driver : car.getDrivers) {
```

2021-01-18 12:15 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +        car.setDrivers(getListDrivers(carId));
here as well we open one connection inside of another

2021-01-18 12:15 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +                + "WHERE cd.driver_id = ? AND c.is_deleted = FALSE;";
let's join `drivers` table as well - we shouldn't fetch info if the driver is deleted

2021-01-18 12:15 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +        }
```suggestion
        try (Connection connection = ConnectionUtil.getConnection();
                PreparedStatement statement = connection.prepareStatement(getCars)) {
            statement.setLong(1, driverId);
            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                cars.add(getCar(resultSet)); // `getCar()` returns only car with manufacturer set
            }
        } catch (SQLException e) {
            throw new DataProcessingException("Can't get list of cars by driverId: " + driverId, e);
        }
        for (Car car : cars) {
            car.setDrivers(getListDrivers(car.getId())); // we fill each car with drivers after the first connection is already closed
        }
```

2021-01-18 12:15 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +    public List<Car> getAll() {
same for this method and `get()`

2021-01-18 12:15 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +        return Optional.ofNullable(car);
```suggestion
        } catch (SQLException e) {
            throw new DataProcessingException("Can't get car by id: " + id, e);
        }
        if (car != null) {
            // set drivers
        }
        return Optional.ofNullable(car);
```

2021-01-19 06:38 UTC, KseniiaMakarova requested changes
good job!

2021-01-19 06:38 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbcImpl.java
> +        String deleteCarsDrivers = "DELETE FROM cars_drivers WHERE car_id = ?;";
let's move the execution of this query into a private method with its own connection

2021-01-19 06:38 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbcImpl.java
> +        createCarsDrivers(car);
```suggestion
            statement.setString(1, car.getModel());
            statement.setLong(2, car.getManufacturer().getId());
            statement.setLong(3, car.getId());
            statement.executeUpdate();
        } catch (SQLException e) {
            throw new DataProcessingException("Can't update table with this car: " + car, e);
        }
        deleteCarsDrivers(car);
        createCarsDrivers(car);
```

2021-01-19 06:38 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbcImpl.java
> +            for (int i = 0; i < car.getDrivers().size(); i++) {
```suggestion
            for (Driver driver : car.getDrivers()) {
```

2021-01-19 11:06 UTC, KseniiaMakarova approved these changes

2021-01-19 11:17 UTC, merged