fifth part
Baldinini/taxi-service pull request #5
Opened 2021-01-19 14:06 UTC by Baldinini

2021-01-19 15:04 UTC, YuraBondarenko approved these changes

2021-01-20 08:44 UTC, dmytro-hryhoruk requested changes

2021-01-20 08:44 UTC, dmytro-hryhoruk commented on pom.xml
> +        </dependency>
do you need this dependency?

2021-01-20 08:44 UTC, dmytro-hryhoruk commented on src/main/webapp/WEB-INF/views/index.jsp
> +
```suggestion
```

2021-01-20 08:44 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +
```suggestion
```

2021-01-20 10:19 UTC, dmytro-hryhoruk approved these changes

2021-01-20 11:39 UTC, merged