seventh part
Baldinini/taxi-service pull request #7
Opened 2021-01-21 20:00 UTC by Baldinini

2021-01-22 10:03 UTC, Max-Pochepets requested changes

2021-01-22 10:03 UTC, Max-Pochepets commented on src/main/java/mate/academy/controllers/driver/GetMyCurrentCarsController.java
> +        req.getRequestDispatcher("/WEB-INF/views/drivers/cars.jsp").forward(req, resp);
```suggestion
        req.getRequestDispatcher("/WEB-INF/views/cars/all.jsp").forward(req, resp);
```
you can use already existing page

2021-01-22 10:03 UTC, Max-Pochepets commented on src/main/java/mate/academy/controllers/driver/LoginController.java
> +        req.getRequestDispatcher("/WEB-INF/views/drivers/login.jsp").forward(req, resp);
```suggestion
        req.getRequestDispatcher("/WEB-INF/views/login.jsp").forward(req, resp);
```
login page should be some sort of a root page

2021-01-22 10:03 UTC, Max-Pochepets commented on src/main/webapp/WEB-INF/views/drivers/login.jsp
> +    Enter your login <input type="text" name="login"><br>
what if I input nothing here?

2021-01-22 10:05 UTC, Max-Pochepets requested changes

2021-01-22 10:05 UTC, Max-Pochepets commented on src/main/java/mate/academy/web/filters/AuthenticationFilter.java
> +        Long driverId = (Long) req.getSession().getAttribute(DRIVER_ID);
check paragraph 5 [checklist](https://mate-academy.github.io/jv-program-fulltime/02_jdbc/checklist/09_filters_checklist.html)

2021-01-22 10:07 UTC, Max-Pochepets requested changes

2021-01-22 10:07 UTC, Max-Pochepets commented on src/main/java/mate/academy/web/filters/AuthenticationFilter.java
> +        }
check paragraph 5 [checklist](https://mate-academy.github.io/jv-program-fulltime/02_jdbc/checklist/09_filters_checklist.html)

2021-01-22 14:02 UTC, Max-Pochepets approved these changes

2021-01-25 16:41 UTC, Sofasmile requested changes

2021-01-25 16:41 UTC, Sofasmile commented on src/main/java/mate/academy/web/filters/AuthenticationFilter.java
> +        if (url.equals("/login") || url.equals("/drivers/add")) {
щоб в майбутньому блок if не розростався краще винести юрлки в сет, який будемо ініціалізовувати в методі  init()
Тоді в блоці if в нас буде єдина умова:  `if(allowedUrls.contains(url))`

2021-01-25 16:41 UTC, Sofasmile commented on src/main/java/mate/academy/security/AuthenticationServiceImpl.java
> +        throw new AuthenticationException("Incorrect driver name or password");
```suggestion
        Optional<Driver> driver = driverService.findByLogin(login);
        if (driver.isPresent() && driver.getPassword().equals(password)) {
            return driver.get();
        }
        throw new AuthenticationException("Incorrect driver name or password");
```

2021-01-26 09:06 UTC, Sofasmile requested changes

2021-01-26 09:06 UTC, Sofasmile commented on src/main/java/mate/academy/web/filters/AuthenticationFilter.java
>      private static final Injector injector = Injector.getInstance("mate.academy");
do we need injector and driverService here?

2021-01-26 09:18 UTC, Sofasmile approved these changes

2021-01-26 10:26 UTC, merged